%YAML 1.1
---
language: python
python:
  - 2.7
  - pypy
  - 3.2
  - 3.3
  - 3.4
install:
  - pip install -e .
  - pip install -r test-requirements.txt
script: nosetests
after_success:
  - coveralls
services:
  - memcached
deploy:
  provider: pypi
  user: sprockets
  on:
    python: 2.7
    tags: true
    all_branches: true
  password:
    secure: F0sivvBoagfbkCnKBlmTEtQXccDRmpfTJSRtL2Vnk8RfsCtoPMEfx8pshuvw5Mp8m6fRxulFd8Qrg3suQjCDFdwlCGxtHricmSfW1LHxNQW/xjDBUvQpdLylv+Am/3CJXso3FZjzji9Z8z5sfBMRUID+jucjhRRbgF68yMUyMXk=
